name = DissertationTalkingDog
mainclass = furhatos.app.dissertationtalkingdog.DissertationtalkingdogSkill
version = 1.0.1
language = en-US
logLevel = INFO
requiresVersion = false
requiresCamera = false
requiresSpeaker = false
requiresMicrophone = false
requiresRecognizer = false

